// frontend/src/routes/settings/components/TaxDefinitionsManager.svelte
<script lang="ts">
  import { getContext } from "svelte";
  import { Plus, Pencil, Trash2 } from "lucide-svelte";
  import { invalidateAll } from "$app/navigation";

  let { taxDefinitions = [], demoMode } = $props();
  let t = getContext("i18n") as (key: string, params?: any) => string;

  let showForm = $state(false);
  let editingId = $state<string | null>(null);
  let formData = $state({
    code: "",
    name: "",
    percent: "",
    countryCode: "",
  });
  let isSubmitting = $state(false);

  function handleAdd() {
    editingId = null;
    formData = { code: "", name: "", percent: "", countryCode: "" };
    showForm = true;
  }

  function handleEdit(tax: any) {
    editingId = tax.id;
    formData = {
      code: tax.code,
      name: tax.name,
      percent: String(tax.percent),
      countryCode: tax.countryCode || "",
    };
    showForm = true;
  }

  function handleCancel() {
    showForm = false;
    editingId = null;
    formData = { code: "", name: "", percent: "", countryCode: "" };
  }

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault();
    isSubmitting = true;
    try {
      const url = editingId ? `/api/v1/tax-definitions/${editingId}` : "/api/v1/tax-definitions";
      const method = editingId ? "PUT" : "POST";
      const res = await fetch(url, {
        method,
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          ...formData,
          percent: parseFloat(formData.percent),
        }),
      });
      if (!res.ok) throw new Error("Failed to save tax definition");
      handleCancel();
      invalidateAll();
    } catch (err) {
      alert(err);
    } finally {
      isSubmitting = false;
    }
  }

  async function handleDelete(tax: any) {
    if (!confirm(t("Delete tax definition confirm", { code: tax.code }))) return;
    try {
      const res = await fetch(`/api/v1/tax-definitions/${tax.id}`, {
        method: "DELETE",
      });
      if (!res.ok) throw new Error("Failed to delete tax definition");
      invalidateAll();
    } catch (err) {
      alert(err);
    }
  }
</script>

<div class="space-y-4">
  <div class="flex items-center justify-between">
    <h3 class="text-lg font-semibold">{t("Tax Definitions")}</h3>
    <button type="button" onclick={handleAdd} class="btn btn-sm btn-primary" disabled={demoMode}>
      <Plus size={16} class="mr-1" />
      {t("Add tax")}
    </button>
  </div>

  {#if showForm}
    <form onsubmit={handleSubmit} class="card bg-base-200 space-y-3 p-4">
      <div class="grid grid-cols-1 gap-3 sm:grid-cols-2">
        <label class="form-control">
          <div class="label">
            <span class="label-text">{t("Tax code")} *</span>
          </div>
          <input type="text" class="input input-bordered w-full" bind:value={formData.code} placeholder={t("Tax code placeholder")} required disabled={demoMode} />
        </label>
        <label class="form-control">
          <div class="label">
            <span class="label-text">{t("Display name")} *</span>
          </div>
          <input type="text" class="input input-bordered w-full" bind:value={formData.name} placeholder={t("Display name placeholder")} required disabled={demoMode} />
        </label>
      </div>

      <div class="grid grid-cols-1 gap-3 sm:grid-cols-2">
        <label class="form-control">
          <div class="label">
            <span class="label-text">{t("Tax Rate (%)")} *</span>
          </div>
          <input type="number" class="input input-bordered w-full" bind:value={formData.percent} step="0.01" min="0" required disabled={demoMode} />
        </label>
        <label class="form-control">
          <div class="label">
            <span class="label-text">{t("Country code")}</span>
          </div>
          <input type="text" class="input input-bordered w-full" bind:value={formData.countryCode} placeholder={t("Country code placeholder")} maxlength="2" disabled={demoMode} />
        </label>
      </div>

      <div class="flex gap-2">
        <button type="submit" class="btn btn-primary" disabled={demoMode || isSubmitting}>
          {editingId ? t("Update") : t("Create")}
        </button>
        <button type="button" onclick={handleCancel} class="btn btn-ghost" disabled={isSubmitting}>
          {t("Cancel")}
        </button>
      </div>
    </form>
  {/if}

  <div class="space-y-2">
    {#if taxDefinitions.length === 0}
      <div class="text-base-content/60 py-6 text-center">
        {t("No tax definitions yet.")}
      </div>
    {:else}
      {#each taxDefinitions as tax (tax.id)}
        <div class="border-base-300 rounded-box bg-base-100 flex items-center justify-between border p-3">
          <div class="flex-1">
            <div class="font-medium">
              {tax.code} &mdash; {tax.name}
            </div>
            <div class="text-base-content/60 text-sm">
              {tax.percent}%
              {#if tax.countryCode}
                &bull; {tax.countryCode}
              {/if}
            </div>
          </div>
          <div class="flex gap-2">
            <button type="button" onclick={() => handleEdit(tax)} class="btn btn-sm btn-ghost" disabled={demoMode} title={t("Edit")}>
              <Pencil size={16} />
            </button>
            <button type="button" onclick={() => handleDelete(tax)} class="btn btn-sm btn-ghost text-error" disabled={demoMode} title={t("Delete")}>
              <Trash2 size={16} />
            </button>
          </div>
        </div>
      {/each}
    {/if}
  </div>
</div>

// frontend/islands/TaxDefinitionsManager.tsx
import { useState } from "preact/hooks";
import { LuPencil, LuPlus, LuTrash2 } from "../components/icons.tsx";
import { useTranslations } from "../i18n/context.tsx";

type TaxDefinition = {
  id: string;
  code: string;
  name: string;
  percent: number;
  countryCode?: string;
  isActive?: boolean;
};

type Props = {
  taxDefinitions: TaxDefinition[];
  demoMode?: boolean;
};

export default function TaxDefinitionsManager(props: Props) {
  const { t } = useTranslations();
  const [showForm, setShowForm] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [formData, setFormData] = useState({
    code: "",
    name: "",
    percent: "",
    countryCode: "",
  });

  const handleAdd = () => {
    setEditingId(null);
    setFormData({ code: "", name: "", percent: "", countryCode: "" });
    setShowForm(true);
  };

  const handleEdit = (tax: TaxDefinition) => {
    setEditingId(tax.id);
    setFormData({
      code: tax.code,
      name: tax.name,
      percent: String(tax.percent),
      countryCode: tax.countryCode || "",
    });
    setShowForm(true);
  };

  const handleCancel = () => {
    setShowForm(false);
    setEditingId(null);
    setFormData({ code: "", name: "", percent: "", countryCode: "" });
  };

  return (
    <div class="space-y-4">
      <div class="flex items-center justify-between">
        <h3 class="text-lg font-semibold">{t("Tax Definitions")}</h3>
        <button
          type="button"
          onClick={handleAdd}
          class="btn btn-sm btn-primary"
          disabled={props.demoMode}
        >
          <LuPlus size={16} class="mr-1" />
          {t("Add tax")}
        </button>
      </div>

      {showForm && (
        <form
          method="post"
          action={editingId
            ? `/api/v1/tax-definitions/${editingId}`
            : "/api/v1/tax-definitions"}
          class="card bg-base-200 p-4 space-y-3"
        >
          {editingId && <input type="hidden" name="_method" value="PUT" />}

          <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <label class="form-control">
              <div class="label">
                <span class="label-text">{t("Tax code")} *</span>
              </div>
              <input
                type="text"
                name="code"
                value={formData.code}
                onInput={(e) =>
                  setFormData({
                    ...formData,
                    code: (e.target as HTMLInputElement).value,
                  })}
                class="input input-bordered w-full"
                placeholder={t("Tax code placeholder")}
                required
                disabled={props.demoMode}
              />
            </label>

            <label class="form-control">
              <div class="label">
                <span class="label-text">{t("Display name")} *</span>
              </div>
              <input
                type="text"
                name="name"
                value={formData.name}
                onInput={(e) =>
                  setFormData({
                    ...formData,
                    name: (e.target as HTMLInputElement).value,
                  })}
                class="input input-bordered w-full"
                placeholder={t("Display name placeholder")}
                required
                disabled={props.demoMode}
              />
            </label>
          </div>

          <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <label class="form-control">
              <div class="label">
                <span class="label-text">{t("Tax Rate (%)")} *</span>
              </div>
              <input
                type="number"
                name="percent"
                value={formData.percent}
                onInput={(e) =>
                  setFormData({
                    ...formData,
                    percent: (e.target as HTMLInputElement).value,
                  })}
                class="input input-bordered w-full"
                step="0.01"
                min="0"
                required
                disabled={props.demoMode}
              />
            </label>

            <label class="form-control">
              <div class="label">
                <span class="label-text">{t("Country code")}</span>
              </div>
              <input
                type="text"
                name="countryCode"
                value={formData.countryCode}
                onInput={(e) =>
                  setFormData({
                    ...formData,
                    countryCode: (e.target as HTMLInputElement).value,
                  })}
                class="input input-bordered w-full"
                placeholder={t("Country code placeholder")}
                maxLength={2}
                disabled={props.demoMode}
              />
            </label>
          </div>

          <div class="flex gap-2">
            <button
              type="submit"
              class="btn btn-primary"
              disabled={props.demoMode}
            >
              {editingId ? t("Update") : t("Create")}
            </button>
            <button type="button" onClick={handleCancel} class="btn btn-ghost">
              {t("Cancel")}
            </button>
          </div>
        </form>
      )}

      <div class="space-y-2">
        {props.taxDefinitions.length === 0
          ? (
            <div class="text-center py-6 text-base-content/60">
              {t("No tax definitions yet.")}
            </div>
          )
          : props.taxDefinitions.map((tax) => (
            <div
              key={tax.id}
              class="flex items-center justify-between p-3 border border-base-300 rounded-box bg-base-100"
            >
              <div class="flex-1">
                <div class="font-medium">
                  {tax.code} — {tax.name}
                </div>
                <div class="text-sm text-base-content/60">
                  {tax.percent}%
                  {tax.countryCode ? ` • ${tax.countryCode}` : ""}
                </div>
              </div>
              <div class="flex gap-2">
                <button
                  type="button"
                  onClick={() => handleEdit(tax)}
                  class="btn btn-sm btn-ghost"
                  disabled={props.demoMode}
                  title={t("Edit")}
                >
                  <LuPencil size={16} />
                </button>
                <form
                  method="post"
                  action={`/api/v1/tax-definitions/${tax.id}`}
                  onSubmit={(e) => {
                    if (
                      !confirm(
                        t("Delete tax definition confirm", { code: tax.code }),
                      )
                    ) {
                      e.preventDefault();
                    }
                  }}
                >
                  <input type="hidden" name="_method" value="DELETE" />
                  <button
                    type="submit"
                    class="btn btn-sm btn-ghost text-error"
                    disabled={props.demoMode}
                    title={t("Delete")}
                  >
                    <LuTrash2 size={16} />
                  </button>
                </form>
              </div>
            </div>
          ))}
      </div>
    </div>
  );
}
