// frontend/islands/ProductOptionsManager.tsx
/**
 * ProductOptionsManager Island
 * Settings UI for managing product categories and units.
 * Allows CRUD operations with deletion protection for items in use.
 */
import { useState } from "preact/hooks";
import { LuPlus, LuPencil, LuTrash2, LuAlertTriangle } from "../components/icons.tsx";
import { useTranslations } from "../i18n/context.tsx";

type ProductCategory = {
  id: string;
  code: string;
  name: string;
  sortOrder: number;
  isBuiltin: boolean;
};

type ProductUnit = {
  id: string;
  code: string;
  name: string;
  sortOrder: number;
  isBuiltin: boolean;
};

type Props = {
  categories: ProductCategory[];
  units: ProductUnit[];
  demoMode?: boolean;
};

export default function ProductOptionsManager(props: Props) {
  const { t } = useTranslations();
  const [categories, setCategories] = useState(props.categories);
  const [units, setUnits] = useState(props.units);
  const [showCategoryForm, setShowCategoryForm] = useState(false);
  const [showUnitForm, setShowUnitForm] = useState(false);
  const [editingCategoryId, setEditingCategoryId] = useState<string | null>(null);
  const [editingUnitId, setEditingUnitId] = useState<string | null>(null);
  const [categoryForm, setCategoryForm] = useState({ code: "", name: "" });
  const [unitForm, setUnitForm] = useState({ code: "", name: "" });
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  // Category handlers
  const handleAddCategory = () => {
    setEditingCategoryId(null);
    setCategoryForm({ code: "", name: "" });
    setShowCategoryForm(true);
    setError(null);
  };

  const handleEditCategory = (cat: ProductCategory) => {
    setEditingCategoryId(cat.id);
    setCategoryForm({ code: cat.code, name: cat.name });
    setShowCategoryForm(true);
    setError(null);
  };

  const handleCancelCategory = () => {
    setShowCategoryForm(false);
    setEditingCategoryId(null);
    setCategoryForm({ code: "", name: "" });
    setError(null);
  };

  const handleSaveCategory = async () => {
    if (!categoryForm.code.trim() || !categoryForm.name.trim()) {
      setError(t("Code and name are required"));
      return;
    }
    setLoading(true);
    setError(null);
    try {
      const url = editingCategoryId
        ? `/api/v1/product-categories/${editingCategoryId}`
        : "/api/v1/product-categories";
      const method = editingCategoryId ? "PUT" : "POST";
      const res = await fetch(url, {
        method,
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(categoryForm),
      });
      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || t("Failed to save category"));
      }
      const saved = await res.json();
      if (editingCategoryId) {
        setCategories(cats => cats.map(c => c.id === saved.id ? saved : c));
      } else {
        setCategories(cats => [...cats, saved]);
      }
      handleCancelCategory();
    } catch (e) {
      setError(String(e));
    } finally {
      setLoading(false);
    }
  };

  const handleDeleteCategory = async (cat: ProductCategory) => {
    if (cat.isBuiltin) {
      setError(t("Cannot delete built-in category"));
      return;
    }
    if (!confirm(t("Delete category confirm", { name: cat.name }))) return;
    setLoading(true);
    setError(null);
    try {
      const res = await fetch(`/api/v1/product-categories/${cat.id}`, { method: "DELETE" });
      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || t("Failed to delete category"));
      }
      setCategories(cats => cats.filter(c => c.id !== cat.id));
    } catch (e) {
      setError(String(e));
    } finally {
      setLoading(false);
    }
  };

  // Unit handlers
  const handleAddUnit = () => {
    setEditingUnitId(null);
    setUnitForm({ code: "", name: "" });
    setShowUnitForm(true);
    setError(null);
  };

  const handleEditUnit = (unit: ProductUnit) => {
    setEditingUnitId(unit.id);
    setUnitForm({ code: unit.code, name: unit.name });
    setShowUnitForm(true);
    setError(null);
  };

  const handleCancelUnit = () => {
    setShowUnitForm(false);
    setEditingUnitId(null);
    setUnitForm({ code: "", name: "" });
    setError(null);
  };

  const handleSaveUnit = async () => {
    if (!unitForm.code.trim() || !unitForm.name.trim()) {
      setError(t("Code and name are required"));
      return;
    }
    setLoading(true);
    setError(null);
    try {
      const url = editingUnitId
        ? `/api/v1/product-units/${editingUnitId}`
        : "/api/v1/product-units";
      const method = editingUnitId ? "PUT" : "POST";
      const res = await fetch(url, {
        method,
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(unitForm),
      });
      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || t("Failed to save unit"));
      }
      const saved = await res.json();
      if (editingUnitId) {
        setUnits(us => us.map(u => u.id === saved.id ? saved : u));
      } else {
        setUnits(us => [...us, saved]);
      }
      handleCancelUnit();
    } catch (e) {
      setError(String(e));
    } finally {
      setLoading(false);
    }
  };

  const handleDeleteUnit = async (unit: ProductUnit) => {
    if (unit.isBuiltin) {
      setError(t("Cannot delete built-in unit"));
      return;
    }
    if (!confirm(t("Delete unit confirm", { name: unit.name }))) return;
    setLoading(true);
    setError(null);
    try {
      const res = await fetch(`/api/v1/product-units/${unit.id}`, { method: "DELETE" });
      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || t("Failed to delete unit"));
      }
      setUnits(us => us.filter(u => u.id !== unit.id));
    } catch (e) {
      setError(String(e));
    } finally {
      setLoading(false);
    }
  };

  return (
    <div class="space-y-6">
      {error && (
        <div class="alert alert-error">
          <LuAlertTriangle size={20} />
          <span>{error}</span>
          <button type="button" class="btn btn-ghost btn-sm" onClick={() => setError(null)}>{t("Dismiss")}</button>
        </div>
      )}

      {/* Categories Section */}
      <div class="space-y-4">
        <div class="flex items-center justify-between">
          <h3 class="text-lg font-semibold">{t("Product Categories")}</h3>
          <button
            type="button"
            onClick={handleAddCategory}
            class="btn btn-sm btn-primary"
            disabled={props.demoMode || loading}
          >
            <LuPlus size={16} class="mr-1" />
            {t("Add category")}
          </button>
        </div>

        {showCategoryForm && (
          <div class="card bg-base-200 p-4 space-y-3">
            <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <label class="form-control">
                <div class="label"><span class="label-text">{t("Code")} *</span></div>
                <input
                  type="text"
                  value={categoryForm.code}
                  onInput={(e) => setCategoryForm({ ...categoryForm, code: (e.target as HTMLInputElement).value })}
                  class="input input-bordered w-full"
                  placeholder={t("Category code placeholder")}
                  disabled={props.demoMode || loading}
                />
              </label>
              <label class="form-control">
                <div class="label"><span class="label-text">{t("Name")} *</span></div>
                <input
                  type="text"
                  value={categoryForm.name}
                  onInput={(e) => setCategoryForm({ ...categoryForm, name: (e.target as HTMLInputElement).value })}
                  class="input input-bordered w-full"
                  placeholder={t("Category name placeholder")}
                  disabled={props.demoMode || loading}
                />
              </label>
            </div>
            <div class="flex gap-2">
              <button type="button" onClick={handleSaveCategory} class="btn btn-primary" disabled={props.demoMode || loading}>
                {loading ? t("Saving...") : (editingCategoryId ? t("Update") : t("Create"))}
              </button>
              <button type="button" onClick={handleCancelCategory} class="btn btn-ghost" disabled={loading}>
                {t("Cancel")}
              </button>
            </div>
          </div>
        )}

        <div class="space-y-2">
          {categories.length === 0 ? (
            <div class="text-center py-6 text-base-content/60">{t("No categories yet.")}</div>
          ) : categories.map((cat) => (
            <div key={cat.id} class="flex items-center justify-between p-3 border border-base-300 rounded-box bg-base-100">
              <div class="flex-1">
                <div class="font-medium">{cat.name}</div>
                <div class="text-sm text-base-content/60">
                  {cat.code}
                  {cat.isBuiltin && <span class="badge badge-ghost badge-sm ml-2">{t("Built-in")}</span>}
                </div>
              </div>
              <div class="flex gap-2">
                <button
                  type="button"
                  onClick={() => handleEditCategory(cat)}
                  class="btn btn-sm btn-ghost"
                  disabled={props.demoMode || loading}
                  title={t("Edit")}
                >
                  <LuPencil size={16} />
                </button>
                {!cat.isBuiltin && (
                  <button
                    type="button"
                    onClick={() => handleDeleteCategory(cat)}
                    class="btn btn-sm btn-ghost text-error"
                    disabled={props.demoMode || loading}
                    title={t("Delete")}
                  >
                    <LuTrash2 size={16} />
                  </button>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>

      <div class="divider"></div>

      {/* Units Section */}
      <div class="space-y-4">
        <div class="flex items-center justify-between">
          <h3 class="text-lg font-semibold">{t("Product Units")}</h3>
          <button
            type="button"
            onClick={handleAddUnit}
            class="btn btn-sm btn-primary"
            disabled={props.demoMode || loading}
          >
            <LuPlus size={16} class="mr-1" />
            {t("Add unit")}
          </button>
        </div>

        {showUnitForm && (
          <div class="card bg-base-200 p-4 space-y-3">
            <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <label class="form-control">
                <div class="label"><span class="label-text">{t("Code")} *</span></div>
                <input
                  type="text"
                  value={unitForm.code}
                  onInput={(e) => setUnitForm({ ...unitForm, code: (e.target as HTMLInputElement).value })}
                  class="input input-bordered w-full"
                  placeholder={t("Unit code placeholder")}
                  disabled={props.demoMode || loading}
                />
              </label>
              <label class="form-control">
                <div class="label"><span class="label-text">{t("Name")} *</span></div>
                <input
                  type="text"
                  value={unitForm.name}
                  onInput={(e) => setUnitForm({ ...unitForm, name: (e.target as HTMLInputElement).value })}
                  class="input input-bordered w-full"
                  placeholder={t("Unit name placeholder")}
                  disabled={props.demoMode || loading}
                />
              </label>
            </div>
            <div class="flex gap-2">
              <button type="button" onClick={handleSaveUnit} class="btn btn-primary" disabled={props.demoMode || loading}>
                {loading ? t("Saving...") : (editingUnitId ? t("Update") : t("Create"))}
              </button>
              <button type="button" onClick={handleCancelUnit} class="btn btn-ghost" disabled={loading}>
                {t("Cancel")}
              </button>
            </div>
          </div>
        )}

        <div class="space-y-2">
          {units.length === 0 ? (
            <div class="text-center py-6 text-base-content/60">{t("No units yet.")}</div>
          ) : units.map((unit) => (
            <div key={unit.id} class="flex items-center justify-between p-3 border border-base-300 rounded-box bg-base-100">
              <div class="flex-1">
                <div class="font-medium">{unit.name}</div>
                <div class="text-sm text-base-content/60">
                  {unit.code}
                  {unit.isBuiltin && <span class="badge badge-ghost badge-sm ml-2">{t("Built-in")}</span>}
                </div>
              </div>
              <div class="flex gap-2">
                <button
                  type="button"
                  onClick={() => handleEditUnit(unit)}
                  class="btn btn-sm btn-ghost"
                  disabled={props.demoMode || loading}
                  title={t("Edit")}
                >
                  <LuPencil size={16} />
                </button>
                {!unit.isBuiltin && (
                  <button
                    type="button"
                    onClick={() => handleDeleteUnit(unit)}
                    class="btn btn-sm btn-ghost text-error"
                    disabled={props.demoMode || loading}
                    title={t("Delete")}
                  >
                    <LuTrash2 size={16} />
                  </button>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// frontend/src/routes/settings/components/ProductOptionsManager.svelte
<script lang="ts">
  import { getContext } from "svelte";
  import { Plus, Pencil, Trash2 } from "lucide-svelte";
  import { invalidateAll } from "$app/navigation";

  let { productCategories = [], productUnits = [], demoMode } = $props();
  let t = getContext("i18n") as (key: string, params?: any) => string;

  let showCategoryForm = $state(false);
  let editingCategoryId = $state<string | null>(null);
  let categoryForm = $state({ code: "", name: "" });

  let showUnitForm = $state(false);
  let editingUnitId = $state<string | null>(null);
  let unitForm = $state({ code: "", name: "" });

  let isSubmitting = $state(false);

  // Categories
  function handleAddCategory() {
    editingCategoryId = null;
    categoryForm = { code: "", name: "" };
    showCategoryForm = true;
  }
  function handleEditCategory(cat: any) {
    editingCategoryId = cat.id;
    categoryForm = { code: cat.code, name: cat.name };
    showCategoryForm = true;
  }
  function handleCancelCategory() {
    showCategoryForm = false;
    editingCategoryId = null;
  }

  async function handleSubmitCategory(e: SubmitEvent) {
    e.preventDefault();
    isSubmitting = true;
    try {
      const url = editingCategoryId ? `/api/v1/product-categories/${editingCategoryId}` : "/api/v1/product-categories";
      const method = editingCategoryId ? "PUT" : "POST";
      const res = await fetch(url, {
        method,
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(categoryForm),
      });
      if (!res.ok) throw new Error("API error");
      handleCancelCategory();
      invalidateAll();
    } catch (err) {
      alert(err);
    } finally {
      isSubmitting = false;
    }
  }

  async function handleDeleteCategory(cat: any) {
    if (!confirm(t("Delete category confirm", { code: cat.code }))) return;
    try {
      await fetch(`/api/v1/product-categories/${cat.id}`, { method: "DELETE" });
      invalidateAll();
    } catch (err) {
      alert(err);
    }
  }

  // Units
  function handleAddUnit() {
    editingUnitId = null;
    unitForm = { code: "", name: "" };
    showUnitForm = true;
  }
  function handleEditUnit(unit: any) {
    editingUnitId = unit.id;
    unitForm = { code: unit.code, name: unit.name };
    showUnitForm = true;
  }
  function handleCancelUnit() {
    showUnitForm = false;
    editingUnitId = null;
  }

  async function handleSubmitUnit(e: SubmitEvent) {
    e.preventDefault();
    isSubmitting = true;
    try {
      const url = editingUnitId ? `/api/v1/product-units/${editingUnitId}` : "/api/v1/product-units";
      const method = editingUnitId ? "PUT" : "POST";
      const res = await fetch(url, {
        method,
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(unitForm),
      });
      if (!res.ok) throw new Error("API error");
      handleCancelUnit();
      invalidateAll();
    } catch (err) {
      alert(err);
    } finally {
      isSubmitting = false;
    }
  }

  async function handleDeleteUnit(unit: any) {
    if (!confirm(t("Delete unit confirm", { code: unit.code }))) return;
    try {
      await fetch(`/api/v1/product-units/${unit.id}`, { method: "DELETE" });
      invalidateAll();
    } catch (err) {
      alert(err);
    }
  }
</script>

<div class="space-y-8">
  <!-- Categories -->
  <div class="space-y-4">
    <div class="border-base-300 flex items-center justify-between border-b pb-2">
      <h3 class="text-lg font-semibold">{t("Product Categories")}</h3>
      <button type="button" onclick={handleAddCategory} class="btn btn-sm btn-primary" disabled={demoMode}>
        <Plus size={16} class="mr-1" />
        {t("Add Category")}
      </button>
    </div>

    {#if showCategoryForm}
      <form onsubmit={handleSubmitCategory} class="card bg-base-200 space-y-3 p-4">
        <div class="grid grid-cols-1 gap-3 sm:grid-cols-2">
          <label class="form-control">
            <div class="label">
              <span class="label-text">{t("Category Code")} *</span>
            </div>
            <input type="text" class="input input-bordered w-full" bind:value={categoryForm.code} required disabled={demoMode} />
          </label>
          <label class="form-control">
            <div class="label">
              <span class="label-text">{t("Category Name")} *</span>
            </div>
            <input type="text" class="input input-bordered w-full" bind:value={categoryForm.name} required disabled={demoMode} />
          </label>
        </div>
        <div class="flex gap-2">
          <button type="submit" class="btn btn-primary" disabled={demoMode || isSubmitting}>{editingCategoryId ? t("Update") : t("Create")}</button>
          <button type="button" onclick={handleCancelCategory} class="btn btn-ghost" disabled={isSubmitting}>{t("Cancel")}</button>
        </div>
      </form>
    {/if}

    <div class="space-y-2">
      {#each productCategories as cat}
        <div class="border-base-300 rounded-box bg-base-100 flex items-center justify-between border p-3">
          <div>
            <span class="font-medium">{cat.code}</span>
            <span class="text-base-content/60">&mdash; {cat.name}</span>
          </div>
          <div class="flex gap-2">
            <button type="button" onclick={() => handleEditCategory(cat)} class="btn btn-sm btn-ghost" disabled={demoMode}><Pencil size={16} /></button>
            <button type="button" onclick={() => handleDeleteCategory(cat)} class="btn btn-sm btn-ghost text-error" disabled={demoMode || cat.isBuiltin}><Trash2 size={16} /></button>
          </div>
        </div>
      {/each}
      {#if productCategories.length === 0}
        <div class="text-base-content/60 py-4 text-center">
          {t("No categories defined")}
        </div>
      {/if}
    </div>
  </div>

  <!-- Units -->
  <div class="space-y-4">
    <div class="border-base-300 flex items-center justify-between border-b pb-2">
      <h3 class="text-lg font-semibold">{t("Product Units")}</h3>
      <button type="button" onclick={handleAddUnit} class="btn btn-sm btn-primary" disabled={demoMode}>
        <Plus size={16} class="mr-1" />
        {t("Add Unit")}
      </button>
    </div>

    {#if showUnitForm}
      <form onsubmit={handleSubmitUnit} class="card bg-base-200 space-y-3 p-4">
        <div class="grid grid-cols-1 gap-3 sm:grid-cols-2">
          <label class="form-control">
            <div class="label">
              <span class="label-text">{t("Unit Code")} *</span>
            </div>
            <input type="text" class="input input-bordered w-full" bind:value={unitForm.code} required disabled={demoMode} />
          </label>
          <label class="form-control">
            <div class="label">
              <span class="label-text">{t("Unit Name")} *</span>
            </div>
            <input type="text" class="input input-bordered w-full" bind:value={unitForm.name} required disabled={demoMode} />
          </label>
        </div>
        <div class="flex gap-2">
          <button type="submit" class="btn btn-primary" disabled={demoMode || isSubmitting}>{editingUnitId ? t("Update") : t("Create")}</button>
          <button type="button" onclick={handleCancelUnit} class="btn btn-ghost" disabled={isSubmitting}>{t("Cancel")}</button>
        </div>
      </form>
    {/if}

    <div class="space-y-2">
      {#each productUnits as unit}
        <div class="border-base-300 rounded-box bg-base-100 flex items-center justify-between border p-3">
          <div>
            <span class="font-medium">{unit.code}</span>
            <span class="text-base-content/60">&mdash; {unit.name}</span>
          </div>
          <div class="flex gap-2">
            <button type="button" onclick={() => handleEditUnit(unit)} class="btn btn-sm btn-ghost" disabled={demoMode}><Pencil size={16} /></button>
            <button type="button" onclick={() => handleDeleteUnit(unit)} class="btn btn-sm btn-ghost text-error" disabled={demoMode || unit.isBuiltin}><Trash2 size={16} /></button>
          </div>
        </div>
      {/each}
      {#if productUnits.length === 0}
        <div class="text-base-content/60 py-4 text-center">
          {t("No units defined")}
        </div>
      {/if}
    </div>
  </div>
</div>
