// frontend/components/InvoiceEditor.tsx
import { JSX } from "preact/jsx-runtime";
import InvoiceEditorIsland from "../islands/InvoiceEditorIsland.tsx";
import { LuPlus, LuGripVertical } from "./icons.tsx";

type Customer = { id: string; name: string };
type Item = {
  description: string;
  quantity: number;
  unitPrice: number;
  notes?: string;
  // Optional single tax percent for UI (maps to a single-entry taxes array backend)
  taxPercent?: number;
};

export function InvoiceEditor(props: {
  mode: "create" | "edit";
  customers?: Customer[];
  selectedCustomerId?: string;
  customerName?: string;
  currency?: string;
  status?: "draft" | "sent" | "paid" | "overdue";
  invoiceNumber?: string;
  invoiceNumberPrefill?: string;
  taxRate?: number;
  pricesIncludeTax?: boolean;
  roundingMode?: string;
  taxMode?: 'invoice' | 'line';
  notes?: string;
  paymentTerms?: string;
  items: Item[];
  showDates?: boolean;
  issueDate?: string;
  dueDate?: string;
  demoMode?: boolean;
  invoiceNumberError?: string;
}): JSX.Element {
  const items = props.items && props.items.length > 0
    ? props.items
    : [{ description: "", quantity: 1, unitPrice: 0 }];
  return (
    <div class="space-y-4">
      {/* Header fields */}
  <div class="grid grid-cols-1 sm:grid-cols-4 gap-3">
        <div class="form-control">
          <div class="label">
            <span class="label-text">Customer <span aria-hidden="true" class="text-error">*</span></span>
          </div>
          {props.mode === "create" && props.customers?.length
            ? (
              <select
                name="customerId"
                class="select select-bordered w-full"
                required
                value={props.selectedCustomerId || ""}
                aria-required="true"
                aria-describedby="customer-error"
              >
                <option value="">Select customer</option>
                {props.customers.map((c) => (
                  <option value={c.id}>{c.name}</option>
                ))}
              </select>
            )
            : (
              <input
                value={props.customerName || ""}
                disabled
                class="input input-bordered w-full"
              />
            )}
          <div id="customer-error" class="text-error text-xs mt-1 hidden"></div>
        </div>
        <div class="form-control">
          <div class="label">
            <span class="label-text">Invoice Number</span>
          </div>
          <input
            name="invoiceNumber"
            value={props.invoiceNumber || props.invoiceNumberPrefill || ""}
            class="input input-bordered w-full"
            placeholder="e.g. INV-2025-001"
            data-writable
            disabled={props.demoMode}
          />
          {props.invoiceNumberError && (
            <div class="text-error text-xs mt-1">{props.invoiceNumberError}</div>
          )}
        </div>
        <div class="form-control">
          <div class="label">
            <span class="label-text">Currency</span>
          </div>
          <input
            name="currency"
            value={props.currency || "USD"}
            class="input input-bordered w-full"
          />
        </div>
        <div class="form-control">
          <div class="label">
            <span class="label-text">Status</span>
          </div>
          <select
            name="status"
            class="select select-bordered w-full"
            value={props.status || "draft"}
          >
            <option value="draft">Draft</option>
            <option value="sent">Sent</option>
            <option value="paid">Paid</option>
            <option value="overdue">Overdue</option>
          </select>
        </div>
      </div>

      {props.showDates && (
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <label class="form-control">
            <div class="label">
              <span class="label-text">Issue Date</span>
            </div>
            <input
              type="date"
              name="issueDate"
              value={props.issueDate || new Date().toISOString().slice(0, 10)}
              class="input input-bordered w-full"
            />
          </label>
          <label class="form-control">
            <div class="label">
              <span class="label-text">Due Date</span>
            </div>
            <input
              type="date"
              name="dueDate"
              value={props.dueDate || ""}
              class="input input-bordered w-full"
            />
          </label>
        </div>
      )}

      {/* Items */}
      <div>
        <div class="flex items-center justify-between mb-2">
          <label class="block text-sm">
            Items <span aria-hidden="true" class="text-error">*</span>
            <span class="ml-2 text-xs text-base-content/50 font-normal">
              (Ctrl+Enter to add)
            </span>
          </label>
          <button type="button" id="add-item" class="btn btn-sm" data-writable disabled={props.demoMode}>
            <LuPlus size={16} />Add item
          </button>
        </div>
        <div id="items-error" class="text-error text-xs mb-2 hidden">Add at least one item with a description.</div>
        
        {/* Column Headers */}
        <div class="items-header hidden sm:flex flex-row flex-nowrap items-center gap-2 mb-1 text-xs text-base-content/60 font-medium">
          <div class="w-6 shrink-0"></div>
          <div class="flex-1 min-w-0 pl-3">Description</div>
          <div class="w-16 sm:w-20 shrink-0 text-center">Quantity</div>
          <div class="w-24 shrink-0 text-center">Price</div>
          <div class="w-24 shrink-0 text-center per-line-tax-input">Tax %</div>
          <div class="w-40 max-w-xs shrink-0 text-center">Notes</div>
          <div class="w-8 shrink-0"></div>
        </div>
        
        <div id="items-container" class="space-y-2">
          {items.map((it) => (
            <div class="item-row flex flex-col sm:flex-row sm:flex-nowrap items-center gap-2" draggable>
              <button
                type="button"
                class="drag-handle btn btn-ghost btn-sm btn-square shrink-0 cursor-move opacity-40 hover:opacity-100"
                aria-label="Drag to reorder"
                tabindex={-1}
              >
                <LuGripVertical size={16} />
              </button>
              <input
                name="item_description"
                value={it.description}
                placeholder="Description"
                class="input input-bordered flex-1 min-w-0"
                data-writable
                disabled={props.demoMode}
                aria-describedby="items-error"
              />
              <input
                type="number"
                step="1"
                min="1"
                name="item_quantity"
                value={String(it.quantity)}
                class="input input-bordered w-16 sm:w-20 shrink-0"
                data-writable
                disabled={props.demoMode}
              />
              <input
                type="number"
                step="0.01"
                min="0"
                name="item_unitPrice"
                value={String(it.unitPrice)}
                class="input input-bordered w-24 shrink-0"
                data-writable
                disabled={props.demoMode}
              />
              <input
                type="number"
                step="0.01"
                min="0"
                name="item_tax_percent"
                value={typeof it.taxPercent === 'number' ? String(it.taxPercent) : ''}
                placeholder="Tax %"
                class="input input-bordered w-24 shrink-0 per-line-tax-input"
                data-writable
                disabled={props.demoMode}
                title="Per-line tax rate (%)"
              />
              <input
                name="item_notes"
                value={it.notes || ""}
                placeholder="Notes"
                class="input input-bordered w-40 max-w-xs shrink-0"
                data-writable
                disabled={props.demoMode}
              />
              <button
                type="button"
                class="remove-item btn btn-ghost btn-square btn-sm shrink-0"
                aria-label="Remove item"
                data-writable
                disabled={props.demoMode}
              >
                ×
              </button>
            </div>
          ))}
        </div>
        <template id="item-template">
          <div class="item-row flex flex-col sm:flex-row sm:flex-nowrap items-center gap-2" draggable>
            <button
              type="button"
              class="drag-handle btn btn-ghost btn-sm btn-square shrink-0 cursor-move opacity-40 hover:opacity-100"
              aria-label="Drag to reorder"
              tabindex={-1}
            >
              <LuGripVertical size={16} />
            </button>
            <input
              name="item_description"
              placeholder="Description"
              class="input input-bordered flex-1 min-w-0"
              data-writable
              disabled={props.demoMode}
              aria-describedby="items-error"
            />
            <input
              type="number"
              step="1"
              min="1"
              name="item_quantity"
              value="1"
              class="input input-bordered w-16 sm:w-20 shrink-0"
              data-writable
              disabled={props.demoMode}
            />
            <input
              type="number"
              step="0.01"
              min="0"
              name="item_unitPrice"
              value="0"
              class="input input-bordered w-24 shrink-0"
              data-writable
              disabled={props.demoMode}
            />
            <input
              type="number"
              step="0.01"
              min="0"
              name="item_tax_percent"
              placeholder="Tax %"
              class="input input-bordered w-24 shrink-0 per-line-tax-input"
              data-writable
              disabled={props.demoMode}
              title="Per-line tax rate (%)"
            />
            <input
              name="item_notes"
              placeholder="Notes"
              class="input input-bordered w-40 max-w-xs shrink-0"
              data-writable
              disabled={props.demoMode}
            />
            <button
              type="button"
              class="remove-item btn btn-ghost btn-square btn-sm shrink-0"
              aria-label="Remove item"
              data-writable
              disabled={props.demoMode}
            >
              ×
            </button>
          </div>
        </template>
      </div>

      {/* Live Totals Preview */}
      <div id="totals-preview" class="bg-base-200 rounded-box p-3 text-sm">
        <div class="flex justify-between items-center gap-4">
          <div class="flex gap-6">
            <div>
              <span class="text-base-content/60">Subtotal:</span>
              <span class="font-semibold ml-2" id="preview-subtotal">—</span>
            </div>
            <div id="preview-tax-container">
              <span class="text-base-content/60">Tax:</span>
              <span class="font-semibold ml-2" id="preview-tax">—</span>
            </div>
          </div>
          <div class="text-right">
            <span class="text-base-content/60">Total:</span>
            <span class="font-bold text-lg ml-2" id="preview-total">—</span>
          </div>
        </div>
      </div>

      {/* Keyboard Shortcuts Help */}
      <div class="text-xs text-base-content/50 flex flex-wrap gap-x-4 gap-y-1">
        <span><kbd class="kbd kbd-xs">Ctrl</kbd>+<kbd class="kbd kbd-xs">S</kbd> Save</span>
        <span><kbd class="kbd kbd-xs">Ctrl</kbd>+<kbd class="kbd kbd-xs">Enter</kbd> Add item</span>
      </div>

      {/* Tax settings */}
      <div class="grid grid-cols-1 sm:grid-cols-4 gap-3">
        <label class="form-control">
          <div class="label">
            <span class="label-text">Tax Mode</span>
          </div>
          <select
            name="taxMode"
            id="tax-mode-select"
            class="select select-bordered w-full"
            value={props.taxMode || 'invoice'}
            disabled={props.demoMode}
          >
            <option value="invoice">Invoice total</option>
            <option value="line">Per line</option>
          </select>
        </label>
        <label class="form-control">
          <div class="label">
            <span class="label-text">Tax Rate (%)</span>
          </div>
          <input
            type="number"
            step="0.01"
            min="0"
            name="taxRate"
            value={String(typeof props.taxRate === 'number' ? props.taxRate : 0)}
            class="input input-bordered w-full"
            data-writable
            disabled={props.demoMode}
            id="invoice-tax-rate-input"
          />
        </label>
        <label class="form-control">
          <div class="label">
            <span class="label-text">Prices include tax?</span>
          </div>
          <select
            name="pricesIncludeTax"
            class="select select-bordered w-full"
            value={(props.pricesIncludeTax ? 'true' : 'false')}
            disabled={props.demoMode}
          >
            <option value="false">No</option>
            <option value="true">Yes</option>
          </select>
        </label>
        <label class="form-control">
          <div class="label">
            <span class="label-text">Rounding mode</span>
          </div>
          <select
            name="roundingMode"
            class="select select-bordered w-full"
            value={props.roundingMode || 'line'}
            disabled={props.demoMode}
          >
            <option value="line">Round per line</option>
            <option value="total">Round on totals</option>
          </select>
        </label>
      </div>

      {/* Payment Terms & Notes */}
      <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
        <label class="form-control">
          <div class="label">
            <span class="label-text">Payment Terms</span>
          </div>
          <input
            name="paymentTerms"
            value={props.paymentTerms || ""}
            placeholder="e.g. Due in 30 days"
            class="input input-bordered w-full"
            data-writable
            disabled={props.demoMode}
          />
        </label>
        <label class="form-control">
          <div class="label">
            <span class="label-text">Notes</span>
          </div>
          <textarea name="notes" class="textarea textarea-bordered" rows={3} data-writable disabled={props.demoMode}>
            {props.notes || ""}
          </textarea>
        </label>
      </div>

      <InvoiceEditorIsland />
    </div>
  );
}

// frontend/src/lib/components/InvoiceEditor.svelte
<script lang="ts">
  import { getContext, onMount, untrack } from "svelte";
  import { Plus, GripVertical } from "lucide-svelte";
  import { goto } from "$app/navigation";

  let { data, invoice = null, formId = "invoice-editor-form" } = $props();
  let initInvoice = untrack(() => invoice);
  let t = getContext("i18n") as (key: string) => string;
  let loc = getContext("localization") as any;

  let saving = $state(false);
  let error = $state("");

  let form = $state({
    customerId: initInvoice?.customerId || "",
    invoiceNumber: initInvoice?.invoiceNumber || "",
    currency: initInvoice?.currency || "EUR",
    status: initInvoice?.status || "draft",
    issueDate: initInvoice?.issueDate ? new Date(initInvoice.issueDate).toISOString().slice(0, 10) : new Date().toISOString().slice(0, 10),
    dueDate: initInvoice?.dueDate ? new Date(initInvoice.dueDate).toISOString().slice(0, 10) : "",
    taxMode: initInvoice?.taxMode || "invoice",
    taxRate: initInvoice?.taxRate || 0,
    pricesIncludeTax: initInvoice?.pricesIncludeTax ? "true" : "false",
    roundingMode: initInvoice?.roundingMode || "line",
    paymentTerms: initInvoice?.paymentTerms || "",
    notes: initInvoice?.notes || ""
  });

  let items = $state(
    initInvoice?.items?.length
      ? initInvoice.items.map((i: any) => ({...i, id: crypto.randomUUID()}))
      : [{ id: crypto.randomUUID(), description: "", quantity: 1, unitPrice: 0, taxPercent: 0, notes: "" }]
  );

  let customers = $derived(data.customers || []);
  let products = $derived(data.products || []);
  let taxDefinitions = $derived(data.taxDefinitions || []);

  function addItem() {
    items.push({ id: crypto.randomUUID(), description: "", quantity: 1, unitPrice: 0, taxPercent: 0, notes: "" });
  }

  function removeItem(index: number) {
    if (items.length > 1) items.splice(index, 1);
  }

  let draggedId = $state<string | null>(null);
  let dragHoverId = $state<string | null>(null);

  function handleDragStart(e: DragEvent, id: string) {
    if (e.dataTransfer) {
      e.dataTransfer.effectAllowed = "move";
      e.dataTransfer.setData("text/plain", id);
    }
    // Defer setting the state to avoid firing dragend immediately
    setTimeout(() => { draggedId = id; }, 0);
  }

  function handleDragOver(e: DragEvent, id: string) {
    e.preventDefault();
    if (!draggedId || draggedId === id) return;
    dragHoverId = id;
    if (e.dataTransfer) {
      e.dataTransfer.dropEffect = "move";
    }
  }

  function handleDragLeave(id: string) {
    if (dragHoverId === id) {
      dragHoverId = null;
    }
  }

  function handleDrop(e: DragEvent, targetId: string) {
    e.preventDefault();
    if (!draggedId || draggedId === targetId) {
      draggedId = null;
      dragHoverId = null;
      return;
    }

    const fromIndex = items.findIndex((i: any) => i.id === draggedId);
    const toIndex = items.findIndex((i: any) => i.id === targetId);

    if (fromIndex !== -1 && toIndex !== -1) {
      const removed = items.splice(fromIndex, 1)[0];
      items.splice(toIndex, 0, removed);
    }

    draggedId = null;
    dragHoverId = null;
  }

  function handleDragEnd() {
    draggedId = null;
    dragHoverId = null;
  }

  function handleKeydown(e: KeyboardEvent) {
    if ((e.ctrlKey || e.metaKey) && e.key === "s") {
      e.preventDefault();
      handleSubmit(e as unknown as SubmitEvent);
    }
    if ((e.ctrlKey || e.metaKey) && e.key === "Enter") {
      e.preventDefault();
      addItem();
    }
  }

  let subtotal = $derived(items.reduce((sum, item) => sum + ((Number(item.quantity) || 0) * (Number(item.unitPrice) || 0)), 0));
  let tax = $derived(form.taxMode === "invoice" ? subtotal * ((Number(form.taxRate) || 0) / 100) : items.reduce((sum, item) => sum + (((Number(item.quantity) || 0) * (Number(item.unitPrice) || 0)) * ((Number(item.taxPercent) || 0) / 100)), 0));
  let total = $derived(form.pricesIncludeTax === "true" ? subtotal : subtotal + tax); // Simplified for visual parity

  async function handleSubmit(e: SubmitEvent | Event) {
    if (e && "preventDefault" in e) e.preventDefault();
    saving = true;
    error = "";

    try {
      const payload = { ...form, pricesIncludeTax: form.pricesIncludeTax === "true", items: items.map(i => ({ description: i.description, quantity: Number(i.quantity), unitPrice: Number(i.unitPrice), taxPercent: Number(i.taxPercent||0), notes: i.notes })) };
      const url = initInvoice ? "/api/v1/invoices/" + initInvoice.id : "/api/v1/invoices";
      const res = await fetch(url, {
        method: initInvoice ? "PUT" : "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload)
      });
      
      if (!res.ok) {
        const d = await res.text();
        let errMsg = "Failed to save invoice";
        try { const j = JSON.parse(d); errMsg = j.error || errMsg; } catch {}
        throw new Error(errMsg);
      }

      const txt = await res.text();
      let result;
      try {
        result = JSON.parse(txt);
      } catch (err: any) {
        throw new Error("JSON parse error: " + err.message + " (Response: " + txt.substring(0, 100) + " )");
      }
      goto("/invoices/" + result.id);
    } catch(err: any) {
      error = err.message;
    } finally {
      saving = false;
    }
  }

  onMount(() => {
    //
  });
</script>

<svelte:window onkeydown={handleKeydown} />

<form id={formId} onsubmit={handleSubmit} class="space-y-6">
  {#if error}
    <div class="alert alert-error">{error}</div>
  {/if}

  <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
    <label class="form-control">
      <div class="label">
        <span class="label-text">{t("Customer")} <span class="text-error">*</span></span>
      </div>
      <select class="select select-bordered w-full" bind:value={form.customerId} required>
        <option value="">{t("Select customer")}</option>
        {#each customers as c}
          <option value={c.id}>{c.name}</option>
        {/each}
      </select>
    </label>

    <label class="form-control">
      <div class="label">
        <span class="label-text">{t("Invoice Number")}</span>
      </div>
      <input type="text" class="input input-bordered w-full" placeholder={t("e.g. INV-2025-001")} bind:value={form.invoiceNumber} />
    </label>

    <label class="form-control">
      <div class="label">
        <span class="label-text">{t("Currency")}</span>
      </div>
      <input type="text" class="input input-bordered w-full" bind:value={form.currency} />
    </label>

    <label class="form-control">
      <div class="label">
        <span class="label-text">{t("Status")}</span>
      </div>
      <select class="select select-bordered w-full" bind:value={form.status}>
        <option value="draft">{t("Draft")}</option>
        <option value="sent">{t("Sent")}</option>
        <option value="paid">{t("Paid")}</option>
        <option value="complete">{t("Complete")}</option>
        <option value="overdue">{t("Overdue")}</option>
        <option value="voided">{t("Voided")}</option>
      </select>
    </label>
  </div>

  <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
    <label class="form-control">
      <div class="label">
        <span class="label-text">{t("Issue Date")}</span>
      </div>
      <input type="date" class="input input-bordered w-full" bind:value={form.issueDate} required />
    </label>

    <label class="form-control">
      <div class="label">
        <span class="label-text">{t("Due Date")}</span>
      </div>
      <input type="date" class="input input-bordered w-full" bind:value={form.dueDate} />
    </label>
  </div>

  <div>
    <div class="flex items-center justify-between mb-2">
      <div class="block text-sm font-semibold">
        {t("Items")} <span class="text-error">*</span>
        <span class="ml-2 text-xs opacity-50 font-normal">({t("Ctrl/Cmd+Enter to add")})</span>
      </div>
      <button type="button" class="btn btn-sm" onclick={addItem}>
        <Plus size={16} />
        <span class="ml-2">{t("Add item")}</span>
      </button>
    </div>

    <div class="hidden lg:flex flex-row flex-nowrap items-center gap-2 mb-1 text-xs opacity-60 font-medium">
      <div class="w-6 shrink-0"></div>
      <div class="flex-1 min-w-0 pl-3">{t("Description")}</div>
      <div class="w-16 sm:w-20 shrink-0 text-center">{t("Quantity")}</div>
      <div class="w-24 shrink-0 text-center">{t("Price")}</div>
      {#if form.taxMode === "line"}
        <div class="w-20 shrink-0 text-center">{t("Tax %")}</div>
      {/if}
      <div class="w-40 max-w-xs shrink-0 text-center">{t("Notes")}</div>
      <div class="w-8 shrink-0"></div>
    </div>

    <div class="space-y-3" role="list">
      {#each items as item, i (item.id)}
        <div role="listitem"
             class="flex flex-nowrap items-center gap-2 p-1 rounded-box transition-colors {draggedId === item.id ? 'opacity-50' : ''} {dragHoverId === item.id ? 'bg-base-200' : ''}"
             draggable="true"
             ondragstart={(e) => handleDragStart(e, item.id)}
             ondragover={(e) => handleDragOver(e, item.id)}
             ondragleave={() => handleDragLeave(item.id)}
             ondrop={(e) => handleDrop(e, item.id)}
             ondragend={handleDragEnd}>
          <button type="button" class="btn btn-ghost btn-sm btn-square shrink-0 cursor-move opacity-40 hover:opacity-100" tabindex="-1">
            <GripVertical size={16} />
          </button>
          
          <input class="input input-bordered w-full min-w-0" bind:value={item.description} placeholder={t("Description")} required />
          <input type="number" min="0" step="1" class="input input-bordered w-16 sm:w-20 shrink-0 text-center" bind:value={item.quantity} />
          <input type="number" min="0" step="any" class="input input-bordered w-24 shrink-0 text-center" bind:value={item.unitPrice} />
          {#if form.taxMode === "line"}
            <input type="number" min="0" step="any" class="input input-bordered w-20 shrink-0 text-center" bind:value={item.taxPercent} placeholder="%" />
          {/if}
          <input class="input input-bordered w-40 max-w-xs shrink-0" bind:value={item.notes} placeholder={t("Notes")} />
          
          <button type="button" class="btn btn-ghost btn-square btn-sm shrink-0" onclick={() => removeItem(i)} aria-label={t("Remove item")}>&times;</button>
        </div>
      {/each}
    </div>

    <div class="mt-6 flex flex-col items-end space-y-2 text-sm">
      <div class="flex justify-between w-48">
        <span>{t("Subtotal")}:</span>
        <span>{subtotal.toFixed(2)}</span>
      </div>
      {#if tax > 0}
      <div class="flex justify-between w-48">
        <span>{t("Tax")}:</span>
        <span>{tax.toFixed(2)}</span>
      </div>
      {/if}
      <div class="flex justify-between w-48 font-bold text-lg">
        <span>{t("Total")}:</span>
        <span>{total.toFixed(2)} {form.currency}</span>
      </div>
    </div>
  </div>

  <div class="flex gap-4 text-xs opacity-50">
    <span class="flex items-center gap-1"><kbd class="kbd kbd-xs">Ctrl</kbd>+<kbd class="kbd kbd-xs">S</kbd> {t("Save")}</span>
    <span class="flex items-center gap-1"><kbd class="kbd kbd-xs">Ctrl</kbd>+<kbd class="kbd kbd-xs">Enter</kbd> {t("Add item")}</span>
  </div>

  <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
    <label class="form-control">
      <div class="label"><span class="label-text">{t("Tax Mode")}</span></div>
      <select class="select select-bordered w-full" bind:value={form.taxMode}>
        <option value="invoice">{t("Invoice total")}</option>
        <option value="line">{t("Per line")}</option>
      </select>
    </label>
    
    <label class="form-control" class:hidden={form.taxMode !== 'invoice'}>
      <div class="label"><span class="label-text">{t("Tax Rate (%)")}</span></div>
      <input type="number" class="input input-bordered w-full" bind:value={form.taxRate} step="any" min="0" />
    </label>

    <label class="form-control">
      <div class="label"><span class="label-text">{t("Prices include tax?")}</span></div>
      <select class="select select-bordered w-full" bind:value={form.pricesIncludeTax}>
        <option value="false">{t("No")}</option>
        <option value="true">{t("Yes")}</option>
      </select>
    </label>

    <label class="form-control">
      <div class="label"><span class="label-text">{t("Rounding mode")}</span></div>
      <select class="select select-bordered w-full" bind:value={form.roundingMode}>
        <option value="line">{t("Round per line")}</option>
        <option value="total">{t("Round on total")}</option>
      </select>
    </label>
  </div>

  <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
    <label class="form-control">
      <div class="label"><span class="label-text">{t("Payment Terms")}</span></div>
      <textarea class="textarea textarea-bordered w-full h-24" bind:value={form.paymentTerms}></textarea>
    </label>
    
    <label class="form-control">
      <div class="label"><span class="label-text">{t("Notes")}</span></div>
      <textarea class="textarea textarea-bordered w-full h-24" bind:value={form.notes}></textarea>
    </label>
  </div>
</form>
